FROM alpine:3.17

ENV VERSION={{ lookup('aws_ssm', '/jinwei-me/tgbot/version') }}
ENV TOKEN ""

WORKDIR /app

ADD https://github.com/iovxw/rssbot/releases/download/${VERSION}/rssbot-en-x86_64-unknown-linux-musl /app/rssbot

RUN chmod +x /app/rssbot

CMD ["sh", "-c", "./rssbot ${TOKEN}"]
