---
collections:
  - name: amazon.aws
    version: 3.2.0
  - name: community.general
    version: 4.7.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.docker
    version: 3.2.1
  - name: community.mysql
    version: 3.5.1
